### ISSUE TITLE
Configure conda packaging

### ISSUE THREAD

**Issue by lukasValentin** [EOA-team/eodal#42]
Apart from bringing EOdal to PyPI publishing EOdal at Anaconda is desired as well.

Following this [guide](https://medium.com/analytics-vidhya/publish-a-python-package-to-conda-b352eb0bcb2e) we therefore need to configure a `meta.yaml` file:

```yaml
package:
  name: "my-py-lib"
  version: "0.1.0"
about:
  summary: "This is an awesome Python library"source:
 path: ..build:
  script: python setup.py install
```

Then we execute `conda build --output-folder ./conda-out/ ./conda/` followed by `anaconda upload ./conda-out/osx-64/my-py-lib-0.1.0-0.tar.bz2`
