### ISSUE TITLE
Mapper: Add information on data source to metadata (e.g.MSPC)

### ISSUE THREAD

**Issue by m-i-g-u-e-l** [EOA-team/eodal#48]
This would help to keep track of the origin of the data.

**Comment by lukasValentin** [comment]
I propose to add the information to the yaml that is created optionally summarizing the main configurations for the mapper.
I would differentiate between:
* local archive as data source
* STAC archive as data source
   - in this case I'd provide the name of the STAC catalog (including its API version)

**Comment by lukasValentin** [comment]
A new attribute `data_source` has been added to the `MapperConfigs` class. The logic behind is

```python
data_source = f'STAC ({settings.STAC_BACKEND.URL})' if  settings.USE_STAC else 'local'
```

Thus, a yaml-file created from the MapperConfigs now looks like:

```yaml
collection: sentinel2-msi
created_at: 2023-05-26 14:58:46.499058
created_by: graflu
data_source: STAC (https://planetarycomputer.microsoft.com/api/stac/v1)
eodal_version: 0.2.0
feature:
  attributes: {}
  epsg: 4326
  geometry: POLYGON ((8.243751434656897 46.93733845009315, 8.236481171106442 47.07964926539655,
    8.477574762024535 47.08246032864037, 8.48254288262916 46.943352951710885, 8.243751434656897
    46.93733845009315))
  name: geometry
metadata_filters:
- cloudy_pixel_percentage < 25
- processing_level == Level-2A
time_end: 2022-06-30 00:00:00
time_start: 2022-06-01 00:00:00

```
In this example, the STAC backend was used to read data from Microsoft Planetary Computer (`data_source: STAC (https://planetarycomputer.microsoft.com/api/stac/v1)`).

To provide backwards-compatibility with older versions, `data_source` is set to `UNKNOWN` when reading a yaml file generated with `EOdal version <=0.2.0`.
